nelmio_api_doc:
    documentation:
        info:
            title: My test api
            description: Api for books
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
